// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/already-reconciled/AnalysisWorkspace.tsx": () => import("../components/mockups/already-reconciled/AnalysisWorkspace.tsx"),
  "./components/mockups/recon-workspace/ActionModalWorkspace.tsx": () => import("../components/mockups/recon-workspace/ActionModalWorkspace.tsx"),
  "./components/mockups/recon-workspace/ModalWorkspace.tsx": () => import("../components/mockups/recon-workspace/ModalWorkspace.tsx"),
  "./components/mockups/recon-workspace/OptionA_ExpandActions.tsx": () => import("../components/mockups/recon-workspace/OptionA_ExpandActions.tsx"),
  "./components/mockups/recon-workspace/OptionB_ContextMenu.tsx": () => import("../components/mockups/recon-workspace/OptionB_ContextMenu.tsx"),
  "./components/mockups/recon-workspace/OptionC_HoverBar.tsx": () => import("../components/mockups/recon-workspace/OptionC_HoverBar.tsx"),
  "./components/mockups/recon-workspace/SummaryWorkspace.tsx": () => import("../components/mockups/recon-workspace/SummaryWorkspace.tsx"),
  "./components/mockups/cancellations/CancellationsWorkspace.tsx": () => import("../components/mockups/cancellations/CancellationsWorkspace.tsx")
};
