// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/recon-workspace/ActionModalWorkspace.tsx": () => import("../components/mockups/recon-workspace/ActionModalWorkspace.tsx"),
  "./components/mockups/recon-workspace/ModalWorkspace.tsx": () => import("../components/mockups/recon-workspace/ModalWorkspace.tsx"),
  "./components/mockups/recon-workspace/SummaryWorkspace.tsx": () => import("../components/mockups/recon-workspace/SummaryWorkspace.tsx")
};
